/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/avAJsjQNo1y
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Link } from 'react-router-dom';
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { SVGProps } from "react"
import { JSX } from "react/jsx-runtime"


export function LandingComponent() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" to="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" to="/weightlifting">Weightlifting</Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" to="/running">Running</Link>
        </nav>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" to="#">
            Features
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" to="#">
            Pricing
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" to="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" to="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-6 md:py-12 lg:py-16 xl:py-20">
          <div className="container flex flex-col items-center justify-center space-y-2 px-4 md:px-6 text-center">
            <div className="space-y-2">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
                Your Fitness Journey Starts Here
              </h1>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Access a variety of workout routines designed to help you reach your fitness goals.
              </p>
            </div>
            <form className="flex flex-col gap-2 min-[400px]:flex-row sm:gap-1.5">
              <Input className="max-w-sm flex-1" placeholder="Enter your email" type="email" />
              <Button size="lg">Get Started</Button>
            </form>
          </div>
        </section>
        <section className="w-full py-12 md:py-16 lg:py-20">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-[1fr_600px] lg:gap-12">
            <img
              alt="Cardio"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="400"
              src="/placeholder.svg"
              width="600"
            />
            <div className="space-y-4">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Cardio</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Burn Calories with Cardio Workouts</h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Improve your cardiovascular health with our fun and engaging cardio workouts. Whether you prefer
                dancing, cycling, or jumping rope, we've got the perfect routines to get your heart pumping.
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-16 lg:py-20 bg-gray-100 dark:bg-gray-800">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-[1fr_600px] lg:gap-12">
            <img
              alt="Strength Training"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="400"
              src="/placeholder.svg"
              width="600"
            />
            <div className="space-y-4">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                Strength Training
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Build Muscle with Strength Training</h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Our strength training programs are designed to help you sculpt and tone your body. From bodyweight
                exercises to weightlifting, we'll guide you through the proper techniques to build strength and
                confidence.
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-16 lg:py-20">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-[1fr_600px] lg:gap-12">
            <img
              alt="Flexibility"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="400"
              src="/placeholder.svg"
              width="600"
            />
            <div className="space-y-4">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Flexibility</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Enhance Your Flexibility with Yoga</h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Embrace the calming practice of yoga and discover the benefits of improved flexibility, balance, and
                mindfulness. Our yoga instructors will lead you through relaxing poses and invigorating flows for all
                levels.
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-16 lg:py-20">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-[600px_1fr] lg:gap-12">
            <div className="space-y-4">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                Success Stories
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Real People, Real Results</h2>
              <div className="space-y-4">
                <div className="flex items-center space-x-4">
                  <img
                    alt="User"
                    className="rounded-full"
                    height="80"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "80/80",
                      objectFit: "cover",
                    }}
                    width="80"
                  />
                  <blockquote className="grid gap-2 text-gray-500 text-justify md:text-base/relaxed lg:text-xl/relaxed xl:text-base-2/relaxed dark:text-gray-400">
                    <p>
                      "Thanks to the amazing workouts on this platform, I was able to lose 20 pounds and feel more
                      energetic than ever. The variety of exercises kept me motivated, and the instructors are
                      fantastic!"
                    </p>
                    <footer className="text-sm font-medium text-gray-500 dark:text-gray-400">
                      — Sarah J., Fitness Enthusiast
                    </footer>
                  </blockquote>
                </div>
                <div className="flex items-center space-x-4">
                  <img
                    alt="User"
                    className="rounded-full"
                    height="80"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "80/80",
                      objectFit: "cover",
                    }}
                    width="80"
                  />
                  <blockquote className="grid gap-2 text-gray-500 text-justify md:text-base/relaxed lg:text-xl/relaxed xl:text-base-2/relaxed dark:text-gray-400">
                    <p>
                      "This platform is a game-changer! The personalized workout plans made it easy for me to stay on
                      track with my fitness goals. I love the convenience of being able to exercise at home, and the
                      support from the community is incredible."
                    </p>
                    <footer className="text-sm font-medium text-gray-500 dark:text-gray-400">
                      — Alex M., Busy Professional
                    </footer>
                  </blockquote>
                </div>
              </div>
            </div>
            <img
              alt="Success Stories"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="400"
              src="/placeholder.svg"
              width="600"
            />
          </div>
        </section>
        <section className="w-full py-12 md:py-16 lg:py-20 border-t">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Ready to Start Your Fitness Journey?
              </h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Sign up to get access to our library of workout videos, expert tips, and community support. Let's make
                every day a step towards a healthier you.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex space-x-2">
                <Input className="max-w-lg flex-1" placeholder="Enter your email" type="email" />
                <Button type="submit">Sign Up</Button>
              </form>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Sign up to get notified when we launch.
                <Link className="underline underline-offset-2" to="#">
                  Terms & Conditions
                </Link>
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-16 lg:py-20 border-t">
          <div className="container grid items-center gap-4 px-4 text-center md:px-6">
            <p className="text-sm text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
            <nav className="flex flex-col gap-2 sm:flex-row">
              <Link className="text-xs hover:underline underline-offset-4" to="#">
                Terms of Service
              </Link>
              <Link className="text-xs hover:underline underline-offset-4" to="#">
                Privacy
              </Link>
            </nav>
          </div>
        </section>
      </main>
    </div>
  )
}

function MountainIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
